name: LumorahAI
description: A new Flutter project.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.0  # Añade esta línea (usa la última versión disponible)
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  provider: ^6.1.2
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  flutter_dotenv: ^5.0.2
  card_swiper: ^3.0.1
  google_sign_in: ^6.2.2
  particles_flutter: ^1.0.1
  lottie: ^3.3.0
  shared_preferences: ^2.0.8
  flutter_sound: ^9.1.2
  audioplayers: ^5.0.0
  http: ^1.1.0
  permission_handler: ^12.0.0+1
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  intl: ^0.19.0  # Opcional, pero útil para formateo
  flutter_launcher_icons: ^0.14.3
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.14
  fl_chart: ^0.71.0
  path_provider: ^2.0.15
  flutter_chat_bubble: ^2.0.2
  timeago: ^3.6.0
  photo_view: ^0.15.0
  share_plus: ^10.1.4
  clipboard: ^0.1.3
  speech_to_text: ^7.0.0
  sign_in_with_apple: ^5.0.0
  flutter_tts: ^4.0.2
  audio_waveforms: ^1.3.0
  avatar_glow: ^2.0.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Elimina intl_utils si ya lo tienes

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/estandar.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/icons/
    - assets/grid/
    - assets/map_style.json
    - assets/logos/
    - .env
    - assets/font/Lora-VariableFont_wght.ttf
    - assets/font/Lora-Italic-VariableFont_wght.ttf
    - assets/translations/  # Añade esta línea para los archivos de traducción
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/font/Inter-Italic-VariableFont_opsz,wght.ttf
          weight: 400
          style: italic
    - family: Lora
      fonts:
        - asset: assets/font/Lora-VariableFont_wght.ttf
          weight: 400
        - asset: assets/font/Lora-Italic-VariableFont_wght.ttf
          weight: 400
          style: italic

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart

# Splash screen configuration
flutter_native_splash:
  color: "#ffffff" # Fondo blanco, cámbialo si lo deseas
  image: assets/icons/estandar.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
